const fs = require('fs');
const path = require('path');

const BT = String.fromCharCode(96);

const content = [
  "'use client';",
  "",
  "import { useState, useRef, useEffect } from 'react';",
  "import { Button } from '@/components/ui/button';",
  "import { Input } from '@/components/ui/input';",
  "import { Card } from '@/components/ui/card';",
  "import { getAccessToken } from '@/lib/api-client';",
  "import Navigation from '@/components/Navigation';",
  "",
  "const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001';",
  "",
  "interface Message {",
  "  role: 'user' | 'assistant';",
  "  content: string;",
  "}",
  "",
  "export default function ChatPage() {",
  "  const [messages, setMessages] = useState<Message[]>([]);",
  "  const [input, setInput] = useState('');",
  "  const [loading, setLoading] = useState(false);",
  "  const [conversationId, setConversationId] = useState<string>();",
  "  const messagesEndRef = useRef<HTMLDivElement>(null);",
  "",
  "  const scrollToBottom = () => {",
  "    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });",
  "  };",
  "",
  "  useEffect(() => {",
  "    scrollToBottom();",
  "  }, [messages]);",
  "",
  "  const handleSendMessage = async (e: React.FormEvent) => {",
  "    e.preventDefault();",
  "    if (!input.trim() || loading) return;",
  "",
  "    const userMessage = input;",
  "    setInput('');",
  "    setMessages((prev) => [...prev, { role: 'user', content: userMessage }]);",
  "    setLoading(true);",
  "",
  "    try {",
  "      const token = await getAccessToken();",
  "      const response = await fetch(" + BT + "${API_URL}/chat/send" + BT + ", {",
  "        method: 'POST',",
  "        headers: {",
  "          'Content-Type': 'application/json',",
  "          'Authorization': " + BT + "Bearer ${token}" + BT + ",",
  "        },",
  "        credentials: 'include',",
  "        body: JSON.stringify({",
  "          conversationId,",
  "          message: userMessage,",
  "        }),",
  "      });",
  "",
  "      if (!response.ok) {",
  "        throw new Error('Failed to send message');",
  "      }",
  "",
  "      setMessages((prev) => [...prev, { role: 'assistant', content: '' }]);",
  "",
  "      let assistantMessage = '';",
  "      const reader = response.body?.getReader();",
  "",
  "      if (reader) {",
  "        const decoder = new TextDecoder();",
  "        let buffer = '';",
  "",
  "        while (true) {",
  "          const { done, value } = await reader.read();",
  "          if (done) break;",
  "",
  "          buffer += decoder.decode(value, { stream: true });",
  "          const parts = buffer.split('\\n\\n');",
  "          buffer = parts.pop() || '';",
  "",
  "          for (const part of parts) {",
  "            if (part.startsWith('event: token')) {",
  "              const dataLine = part.split('\\n').find(l => l.startsWith('data: '));",
  "              if (dataLine) {",
  "                try {",
  "                  const data = JSON.parse(dataLine.slice(6));",
  "                  assistantMessage += data.token;",
  "                  setMessages((prev) => {",
  "                    const updated = [...prev];",
  "                    const lastMsg = updated[updated.length - 1];",
  "                    if (lastMsg && lastMsg.role === 'assistant') {",
  "                      lastMsg.content = assistantMessage;",
  "                    }",
  "                    return updated;",
  "                  });",
  "                } catch (e) {}",
  "              }",
  "            } else if (part.startsWith('event: complete')) {",
  "              const dataLine = part.split('\\n').find(l => l.startsWith('data: '));",
  "              if (dataLine) {",
  "                try {",
  "                  const data = JSON.parse(dataLine.slice(6));",
  "                  if (data.conversationId) {",
  "                    setConversationId(data.conversationId);",
  "                  }",
  "                } catch (e) {}",
  "              }",
  "            }",
  "          }",
  "        }",
  "      }",
  "    } catch (error) {",
  "      console.error('Error:', error);",
  "      setMessages((prev) => [",
  "        ...prev,",
  "        { role: 'assistant', content: 'Error: Failed to get response' },",
  "      ]);",
  "    } finally {",
  "      setLoading(false);",
  "    }",
  "  };",
  "",
  "  return (",
  "    <div className=\"flex h-screen flex-col bg-slate-50\">",
  "      <Navigation />",
  "",
  "      <main className=\"flex flex-1 flex-col overflow-hidden\">",
  "        <div className=\"flex-1 overflow-auto space-y-4 p-8\">",
  "          {messages.length === 0 ? (",
  "            <div className=\"flex h-full items-center justify-center text-slate-500\">",
  "              <p>Start a conversation with your AI copilot</p>",
  "            </div>",
  "          ) : (",
  "            messages.map((msg, idx) => (",
  "              <div",
  "                key={idx}",
  "                className={" + BT + "flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}" + BT + "}",
  "              >",
  "                <Card",
  "                  className={" + BT + "max-w-md px-4 py-2 ${",
  "                    msg.role === 'user'",
  "                      ? 'bg-blue-600 text-white'",
  "                      : 'bg-slate-200 text-slate-900'",
  "                  }" + BT + "}",
  "                >",
  "                  <p className=\"whitespace-pre-wrap\">{msg.content}</p>",
  "                </Card>",
  "              </div>",
  "            ))",
  "          )}",
  "          <div ref={messagesEndRef} />",
  "        </div>",
  "",
  "        <div className=\"border-t border-slate-200 bg-white p-4\">",
  "          <form onSubmit={handleSendMessage} className=\"mx-auto flex max-w-4xl gap-2\">",
  "            <Input",
  "              type=\"text\"",
  "              placeholder=\"Ask your AI copilot...\"",
  "              value={input}",
  "              onChange={(e) => setInput(e.target.value)}",
  "              disabled={loading}",
  "              className=\"flex-1\"",
  "            />",
  "            <Button type=\"submit\" disabled={loading}>",
  "              {loading ? 'Thinking...' : 'Send'}",
  "            </Button>",
  "          </form>",
  "        </div>",
  "      </main>",
  "    </div>",
  "  );",
  "}"
].join('\n');

const targetPath = path.join(__dirname, '..', 'app', '(protected)', 'chat', 'page.tsx');
fs.writeFileSync(targetPath, content, 'utf8');
console.log('File written successfully');
